[package]
name = "concept-graph-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
fnv = "1.0.7"
pulldown-cmark = "0.13.0"
rand = "0.9.2"
rayon = "1.11.0"
regex = "1.11.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
walkdir = "2.5.0"
